# Generated by Django 4.2.11 on 2024-03-22 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('statement', models.TextField(blank=True, null=True)),
                ('answer_a', models.CharField(max_length=30)),
                ('answer_b', models.CharField(max_length=30)),
                ('answer_c', models.CharField(max_length=30)),
                ('answer_d', models.CharField(max_length=30)),
                ('correct_answer', models.CharField(max_length=30)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
    ]
