# Generated by Django 4.2.11 on 2024-03-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_quiz_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
